use Mix.Config

# Configure your database
config :newsfeed, Newsfeed.Repo,
  username: "postgres",
  password: "postgres",
  database: "newsfeed_dev",
  hostname: "localhost",  # Use localhost when running on the host machine
  show_sensitive_data_on_connection_error: true,
  pool_size: 10

# For development, we disable any cache and enable
# debugging and code reloading.
#
# The watchers configuration can be used to run external
# watchers to your application. For example, we use it
# with webpack to recompile .js and .css sources.
config :newsfeed, NewsfeedWeb.Endpoint,
  http: [port: 4000],
  debug_errors: true,
  code_reloader: true,
  check_origin: false,
  watchers: [
    node: [
      "node_modules/webpack/bin/webpack.js",
      "--mode",
      "development",
      "--watch-stdin",
      cd: Path.expand("../assets", __DIR__)
    ]
  ]

# Add Kafka/Redpanda configuration
config :newsfeed, :kafka,
  brokers: [{"localhost", 9092}],  # Use localhost when running on the host machine
  client_id: "newsfeed_app"

# Redis configuration
config :newsfeed, :redis,
  host: "localhost",  # Use localhost when running on the host machine
  port: 6379

# RabbitMQ configuration
config :newsfeed, :rabbitmq,
  host: "localhost",  # Use localhost when running on the host machine
  port: 5672,
  username: "guest",
  password: "guest"

# ActiveMQ configuration
config :newsfeed, :activemq,
  host: "localhost",  # Use localhost when running on the host machine
  port: 61616

# ## SSL Support
#
# In order to use HTTPS in development, a self-signed
# certificate can be generated by running the following
# Mix task:
#
#     mix phx.gen.cert
#
# Note that this task requires Erlang/OTP 20 or later.
# Run `mix help phx.gen.cert` for more information.
#
# The `http:` config above can be replaced with:
#
#     https: [
#       port: 4001,
#       cipher_suite: :strong,
#       keyfile: "priv/cert/selfsigned_key.pem",
#       certfile: "priv/cert/selfsigned.pem"
#     ],
#
# If desired, both `http:` and `https:` keys can be
# configured to run both http and https servers on
# different ports.

# Watch static and templates for browser reloading.
config :newsfeed, NewsfeedWeb.Endpoint,
  live_reload: [
    patterns: [
      ~r"priv/static/.*(js|css|png|jpeg|jpg|gif|svg)$",
      ~r"priv/gettext/.*(po)$",
      ~r"lib/newsfeed_web/(live|views)/.*(ex)$",
      ~r"lib/newsfeed_web/templates/.*(eex)$"
    ]
  ]

# Do not include metadata nor timestamps in development logs
config :logger, :console, format: "[$level] $message\n"

# Set a higher stacktrace during development. Avoid configuring such
# in production as building large stacktraces may be expensive.
config :phoenix, :stacktrace_depth, 20

# Initialize plugs at runtime for faster development compilation
config :phoenix, :plug_init_mode, :runtime
